<?php
/**
 * Created by PhpStorm.
 * User: Chris
 * Date: 1/29/16
 * Time: 12:39 PM
 */

// ====================  Session Fields ===============//

$wpmt_session_fields = array (
    array (
        'key' => 'field_56a12595938bf',
        'label' => 'Session Start',
        'name' => 'wpmt_session_start',
        'type' => 'text',
        'instructions' => 'in veezi: FeatureStartTime
	sample: 2016-01-14T18:30:00',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a1261d938c0',
        'label' => 'Session End',
        'name' => 'wpmt_session_end',
        'type' => 'text',
        'instructions' => 'Veezi field: FeatureEndTime
	sample: 2016-01-14T19:04:00',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a12574938be',
        'label' => 'Film ID',
        'name' => 'wpmt_session_film_id',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a12677938c1',
        'label' => 'Film Title',
        'name' => 'wpmt_session_film_title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a126f7938c4',
        'label' => 'Session Status',
        'name' => 'wpmt_session_status',
        'type' => 'text',
        'instructions' => 'valid values:
	Open
	Closed
	Planned',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56ab9c1f2bc2c',
        'label' => 'Screen ID',
        'name' => 'wpmt_session_screen_id',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a126bb938c3',
        'label' => 'Seats Available',
        'name' => 'wpmt_session_seats_available',
        'type' => 'number',
        'instructions' => 'SeatsAvailable',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
    ),
    array (
        'key' => 'field_56af703f7a2ba',
        'label' => 'Ticket Server URL',
        'name' => 'wpmt_session_ticket_url',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
    ),
);


// ====================  Film Fields ==================//

$wpmt_film_fields = array (
    array (
        'key' => 'field_56a10c7a26578',
        'label' => 'Ticket Server Film ID',
        'name' => 'wpmt_film_id',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a10d337a3d1',
        'label' => 'Ticket Server Short Name',
        'name' => 'wpmt_film_short_name',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a111df1ffab',
        'label' => 'Ticket Server status',
        'name' => 'wpmt_film_status',
        'type' => 'text',
        'instructions' => 'veezi valid values:
	Active
	Inactive
	Deleted',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56b571dec2eaf',
        'label' => 'Next Session Start time',
        'name' => 'wpmt_film_start',
        'type' => 'text',
        'instructions' => 'sample: 2014-08-15T00:00:00',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a118f80afd1',
        'label' => 'Ticket Server opening date',
        'name' => 'wpmt_film_opening_date',
        'type' => 'text',
        'instructions' => 'sample: 2014-08-15T00:00:00',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56ab9761e9e1e',
        'label' => 'Film Format',
        'name' => 'wpmt_film_format',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a10e0618f4a',
        'label' => 'Synopsis',
        'name' => 'wpmt_film_synopsis',
        'type' => 'textarea',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'br',
    ),
    array (
        'key' => 'field_56a10e1918f4b',
        'label' => 'Genre',
        'name' => 'wpmt_film_genre',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a10e3118f4c',
        'label' => 'Rating',
        'name' => 'wpmt_film_rating',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a10eb518f4e',
        'label' => 'Duration',
        'name' => 'wpmt_film_duration',
        'type' => 'number',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
    ),
    array (
        'key' => 'field_56a11844f6114',
        'label' => 'Distributor',
        'name' => 'wpmt_film_distributor',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a10ef718f50',
        'label' => 'Language',
        'name' => 'wpmt_film_audio_language',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a1185ff6115',
        'label' => 'Directors',
        'name' => 'wpmt_film_directors',
        'type' => 'text',
        'instructions' => 'list directors here, separate by commas',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a11869f6116',
        'label' => 'Actors',
        'name' => 'wpmt_film_actors',
        'type' => 'text',
        'instructions' => 'list actors here, separate by commas',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a119ad9561d',
        'label' => 'Content Advisory',
        'name' => 'wpmt_film_content_advisory',
        'type' => 'text',
        'instructions' => 'ie: Rated PG-13 for a mature thematic image and some sci-fi action/violence.',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a113b2b02a2',
        'label' => 'Film Poster',
        'name' => 'wpmt_film_poster',
        'type' => 'image',
        'instructions' => 'vertical poster approx. 250x366',
        'save_format' => 'id',
        'preview_size' => 'wpmt_poster',
        'library' => 'all',
    ),
    array (
        'key' => 'field_56a1147cb02a3',
        'label' => 'Film Key Image',
        'name' => 'wpmt_film_image',
        'type' => 'image',
        'instructions' => 'film featured image. Approx. 480x290',
        'save_format' => 'id',
        'preview_size' => 'wpmt_image',
        'library' => 'all',
    ),
    array (
        'key' => 'field_56a11673b02a5',
        'label' => 'Hide this film from website',
        'name' => 'wpmt_film_hide',
        'type' => 'true_false',
        'instructions' => 'check this box if you want to prevent this film from showing up on the website.	Useful for test veezi entries, etc.',
        'message' => '',
        'default_value' => 0,
    ),
    array (
        'key' => 'field_56a11735b02a6',
        'label' => 'free',
        'name' => 'wpmt_film_free',
        'type' => 'true_false',
        'instructions' => 'only check this if all screenings of this film are free',
        'message' => '',
        'default_value' => 0,
    ),
    array (
        'key' => 'field_56a1178eb02a7',
        'label' => 'youtube trailer URL',
        'name' => 'wpmt_film_youtube_url',
        'type' => 'text',
        'instructions' => 'full URL from youtube trailer',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56b0a4dd84ab1',
        'label' => 'Rotten Tomatoes Rating',
        'name' => 'wpmt_film_rt_rating',
        'type' => 'text',
        'instructions' => 'only save if fresh (60% or higher)',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56b0a4f084ab2',
        'label' => 'Rotten Tomatoes Consensus',
        'name' => 'wpmt_film_rt_consensus',
        'type' => 'textarea',
        'instructions' => 'only save if movie rated 70% or higher',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56a117eab02a8',
        'label' => 'reviews',
        'name' => 'wpmt_film_reviews',
        'type' => 'textarea',
        'instructions' => 'copy and paste reviews here (optional)',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'br',
    ),
);


// ====================  Performance Fields ===========//

$wpmt_performance_fields = array (
    array (
        'key' => 'field_56afa3a5d0b6d',
        'label' => 'Ticket Server Performance ID',
        'name' => 'wpmt_performance_id',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa6c0d0b6e',
        'label' => 'Ticket Server Short Name',
        'name' => 'wpmt_film_performance_name',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa6cad0b6f',
        'label' => 'Ticket Server status',
        'name' => 'wpmt_performance_status',
        'type' => 'text',
        'instructions' => 'veezi valid values:
	Active
	Inactive
	Deleted',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56bebae941137',
        'label' => 'Next Session Start time',
        'name' => 'wpmt_performance_start',
        'type' => 'text',
        'instructions' => 'sample: 2014-08-15T00:00:00',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa6d1d0b70',
        'label' => 'Ticket Server opening date',
        'name' => 'wpmt_performance_opening_date',
        'type' => 'text',
        'instructions' => 'sample:
	2014-08-15T00:00:00',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa6ddd0b71',
        'label' => 'Performance Format',
        'name' => 'wpmt_performance_format',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa6e4d0b72',
        'label' => 'Synopsis',
        'name' => 'wpmt_performance_synopsis',
        'type' => 'textarea',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'br',
    ),
    array (
        'key' => 'field_56afa6e9d0b73',
        'label' => 'Genre',
        'name' => 'wpmt_performance_genre',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa983d0b74',
        'label' => 'Rating',
        'name' => 'wpmt_performance_rating',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa98ad0b75',
        'label' => 'Duration',
        'name' => 'wpmt_performance_duration',
        'type' => 'number',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
    ),
    array (
        'key' => 'field_56afa98fd0b76',
        'label' => 'Distributor',
        'name' => 'wpmt_performance_distributor',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa994d0b77',
        'label' => 'Language',
        'name' => 'wpmt_performance_audio_language',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa99cd0b78',
        'label' => 'Directors',
        'name' => 'wpmt_performance_directors',
        'type' => 'text',
        'instructions' => 'list directors here, separate by commas',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa9a9d0b79',
        'label' => 'Actors',
        'name' => 'wpmt_performance_actors',
        'type' => 'text',
        'instructions' => 'list actors here, separate by commas',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa9b0d0b7a',
        'label' => 'Content Advisory',
        'name' => 'wpmt_performance_content_advisory',
        'type' => 'text',
        'instructions' => 'ie: Rated PG-13 for a mature thematic image and some sci-fi action/violence.
	 ',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa9b7d0b7b',
        'label' => 'Performance Poster',
        'name' => 'wpmt_performance_poster',
        'type' => 'image',
        'instructions' => 'vertical poster approx. 250x366',
        'save_format' => 'id',
        'preview_size' => 'wpmt_poster',
        'library' => 'all',
    ),
    array (
        'key' => 'field_56afa9c1d0b7c',
        'label' => 'Performance Key Image',
        'name' => 'wpmt_performance_image',
        'type' => 'image',
        'instructions' => 'Performance featured image. Approx. 480x290',
        'save_format' => 'id',
        'preview_size' => 'wpmt_poster',
        'library' => 'all',
    ),
    array (
        'key' => 'field_56afa9c7d0b7d',
        'label' => 'Hide this performance from website',
        'name' => 'wpmt_performance_hide',
        'type' => 'true_false',
        'instructions' => 'check this box if you want to prevent this performance from showing up on the website.	Useful for test veezi entries, etc.',
        'message' => '',
        'default_value' => 0,
    ),
    array (
        'key' => 'field_56afa9ccd0b7e',
        'label' => 'free',
        'name' => 'wpmt_performance_free',
        'type' => 'true_false',
        'instructions' => 'only check this if all screenings of this performance are free',
        'message' => '',
        'default_value' => 0,
    ),
    array (
        'key' => 'field_56afa9d2d0b7f',
        'label' => 'youtube video URL',
        'name' => 'wpmt_performance_youtube_url',
        'type' => 'text',
        'instructions' => 'full URL from youtube',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
    ),
    array (
        'key' => 'field_56afa9d8d0b80',
        'label' => 'reviews',
        'name' => 'wpmt_performance_reviews',
        'type' => 'textarea',
        'instructions' => 'copy and paste reviews here (optional)',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'br',
    ),
);



if(function_exists("register_field_group"))
{
    // ====================  Sessions Post Type ===============//

    register_field_group(array (
        'id' => 'acf_wpmt-session-fields',
        'title' => 'WPMT Session Fields',
        'fields' => $wpmt_session_fields,
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'wpmt_session',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
                //0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));


    // ====================  Films Post Type ==================//

    register_field_group(array (
        'id' => 'acf_wpmt-film-fields',
        'title' => 'WPMT Film Fields',
        'fields' => $wpmt_film_fields,
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'wpmt_film',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'user_type',
                    'operator' => '==',
                    'value' => 'administrator',
                    'order_no' => 1,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
                //0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 1,
    ));


    // ============  Performances Post Type ===============//

    register_field_group(array (
        'id' => 'acf_wpmt-performance-admin-fields',
        'title' => 'WPMT Performance Admin Fields',
        'fields' => $wpmt_performance_fields,
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'wpmt_performance',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
                array (
                    'param' => 'user_type',
                    'operator' => '==',
                    'value' => 'administrator',
                    'order_no' => 1,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
                //0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 1,
    ));

} //end if



// ====================  FUNCTIONS =======================//


function get_wpmt_film_fields_ref() {
    global $wpmt_film_fields;
    return make_wpmt_fields_ref( $wpmt_film_fields );
}


function get_wpmt_performance_fields_ref() {
    global $wpmt_performance_fields;
    return make_wpmt_fields_ref( $wpmt_performance_fields );
}


function get_wpmt_session_fields_ref() {
    global $wpmt_session_fields;
    return make_wpmt_fields_ref( $wpmt_session_fields );
}


function make_wpmt_fields_ref( $acf_fields_arr ) {

    $wpmt_fields_ref = array ();
    foreach ( $acf_fields_arr as $key => $value ) {
        $wpmt_fields_ref [$value['name']] = $value['key'];
    }
    return $wpmt_fields_ref;
}